version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/:/usr/share/nginx/html/
    ports:
      - 8000:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
    environment:
      PYTHONPATH: .
